stages:
  - name: Build image
    steps:
      - publishImageConfig:
          dockerfilePath: ./Dockerfile --build-args BASE_IMAGE_TAG=9.11.2
          buildContext: .
          tag: node:${CICD_EXECUTION_SEQUENCE}
  - name: Deploy
    steps:
      - applyYamlConfig:
          path: ./deploy/deployment.yaml
