stages:
- name: Build image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: node:${CICD_EXECUTION_SEQUENCE}
      registry: 127.0.0.1:34552
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deploy/deployment.yaml
