kind: Service
apiVersion: v1
metadata:
  name: node-service
spec:
  selector:
    app: node
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
  labels:
    app: node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: node
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 3000
